name: Update Pac-Man Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Pac-Man Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: divyadeepmishra
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # theme: "dark"
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/pacman-contribution-graph.svg output/pacman-contribution-graph-dark.svg
          git commit -m "Update Pac-Man graph"
          git push
