name: Generate Pac-Man Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    # Set permissions to allow pushing to the repository
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the Pac-Man contribution graph
      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          # GitHub username to generate the animation for
          github_user_name: ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: (Optional) Commit and push the generated files to the main branch
      # NOTE: The Pac-Man action already commits to the 'output' folder,
      # but if you want to ensure files are in your main branch, uncomment below.
      # - name: Commit and Push Generated Files
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"
      #     git add output/pacman-contribution-graph.svg
      #     git commit -m "Update Pac-Man graph [skip ci]" || echo "No changes to commit"
      #     git push
